### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by splitbrain** [SirPole/google-fonts-plugin#5]
When I add this plugin to my webpack config I get the following error:

```
Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (/home/gohr/public_html/wmtng/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/gohr/public_html/wmtng/node_modules/google-fonts-plugin/dist/index.js:3:30)
    at Module._compile (/home/gohr/public_html/wmtng/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (/home/gohr/public_html/wmtng/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/gohr/public_html/wmtng/webpack.config.js:5:27)
    at Module._compile (/home/gohr/public_html/wmtng/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (/home/gohr/public_html/wmtng/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/gohr/public_html/wmtng/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/home/gohr/public_html/wmtng/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /home/gohr/public_html/wmtng/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/gohr/public_html/wmtng/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/home/gohr/public_html/wmtng/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/home/gohr/public_html/wmtng/node_modules/yargs/yargs.js:563:18)
    at /home/gohr/public_html/wmtng/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/home/gohr/public_html/wmtng/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
```

It seems there is some incompatibilty with my babel setup, but I have no idea what the problem is. HEre are my dependencies:

```
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.6",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "css-loader": "^1.0.0",
    "eslint": "^5.2.0",
    "eslint-config-airbnb-base": "^13.0.0",
    "eslint-loader": "^2.1.0",
    "eslint-plugin-eslint-comments": "^3.0.1",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-typelint": "^1.0.9",
    "eslint-plugin-unicorn": "^5.0.0",
    "google-fonts-plugin": "^2.0.1",
    "mini-css-extract-plugin": "^0.4.1",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "stylelint": "^9.4.0",
    "stylelint-config-standard": "^18.2.0",
    "stylelint-webpack-plugin": "^0.10.5",
    "webpack": "^4.16.3",
    "webpack-cli": "^3.1.0"
  }
```

Any idea what's wrong?

**Comment by SirPole** [comment]
Hello,

I've accidentally left in babel transform-runtime plugin which requires @babel/runtime. I have removed it now and version `2.0.2` should work for you! Please let me know if it does and close the issue then, thank you 🙂

**Comment by splitbrain** [comment]
works :+1:
